/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jai.aws.dynamodb;

import com.jai.aws.dynamodb.model.Address;
import com.jai.aws.dynamodb.model.Employee;
import org.junit.Test;

import static org.junit.Assert.*;

public class ApplicationTest {

    Application application = new Application();

    @Test
    public void testSomeLibraryMethod() {
        Employee employee = new Employee();
        employee.setEmployeeName("jjay");
        employee.setPhone("1234567890");

        Address homeAddress = new Address();
        homeAddress.setFirstLine("788, Shenoy Nagar");
        homeAddress.setSecondLine("Port Road");
        homeAddress.setCity("Mumbai");
        homeAddress.setCountry("India");

        Address workAddress = new Address();
        workAddress.setFirstLine("10, Gandhi Nagar");
        workAddress.setSecondLine("Great Road");
        workAddress.setCity("Delhi");
        workAddress.setCountry("India");

        employee.setHomeAddress(homeAddress);
        employee.setWorkAddress(workAddress);
        application.create(employee);

    }
}
