/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jai.aws.dynamodb;

import org.junit.Test;

import static org.junit.Assert.*;

public class ApplicationTest {

    Application application = new Application();

    @Test
    public void testSomeLibraryMethod() {
        application.create();

    }
}
