/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jai.aws.dynamodb;

import com.jai.aws.dynamodb.model.Address;
import com.jai.aws.dynamodb.model.Employee;
import org.junit.Test;
import software.amazon.awssdk.services.dynamodb.model.DeleteItemResponse;
import software.amazon.awssdk.services.dynamodb.model.ScanResponse;

public class EmployeeServiceTest {

    EmployeeService application = new EmployeeService();

    @Test
    public void testSomeLibraryMethod() {
        Employee employee = new Employee();
        employee.setEmployeeName("jjay");
        employee.setPhone("1234567890");

        Address homeAddress = new Address();
        homeAddress.setFirstLine("788, Shenoy Nagar");
        homeAddress.setSecondLine("Port Road");
        homeAddress.setCity("Mumbai");
        homeAddress.setCountry("India");

        Address workAddress = new Address();
        workAddress.setFirstLine("10, Gandhi Nagar");
        workAddress.setSecondLine("Great Road");
        workAddress.setCity("Delhi");
        workAddress.setCountry("India");

        employee.setHomeAddress(homeAddress);
        employee.setWorkAddress(workAddress);
        application.create(employee);

    }

    @Test
    public void delete() {
        String employeeId = "e8b23563-ec23-4886-97b9-e4364a867271";
        DeleteItemResponse response = application.delete(employeeId);
        System.out.println(response);
    }

    @Test
    public void getAllTables(){
        System.out.println(application.getAllTables());
    }

    @Test
    public void readAll(){
        ScanResponse scanResponse = application.readAll();
        System.out.println(scanResponse.count());
        scanResponse.items().forEach(System.out::println);
    }
}
