package com.jai.dynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName = "Employee")
@Data
@NoArgsConstructor
public class Employee {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String employeeId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String city;

}
