/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jai.aws.dynamodb;

import com.jai.aws.dynamodb.model.Employee;
import com.jai.aws.dynamodb.repository.EmployeeRepository;

import javax.xml.transform.Templates;

public class Application {

    private static EmployeeRepository employeeRepository;

    public Application() {
        employeeRepository = new EmployeeRepository();
    }

    public void create(Employee employee) {
        employeeRepository.create(employee);
    }


}
