/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jai.aws.dynamodb;

import com.jai.aws.dynamodb.model.Employee;
import com.jai.aws.dynamodb.repository.EmployeeRepository;
import software.amazon.awssdk.services.dynamodb.model.DeleteItemResponse;
import software.amazon.awssdk.services.dynamodb.model.Put;
import software.amazon.awssdk.services.dynamodb.model.PutItemResponse;
import software.amazon.awssdk.services.dynamodb.model.ScanResponse;

import javax.xml.transform.Templates;
import java.util.List;

public class EmployeeService {

    private static EmployeeRepository employeeRepository;

    public EmployeeService() {
        employeeRepository = new EmployeeRepository();
    }

    public ScanResponse readAll() {
        return employeeRepository.readAll();
    }

    public List<String> getAllTables() {
        return employeeRepository.getAllTables();
    }

    public PutItemResponse create(Employee employee) {
        return employeeRepository.create(employee);
    }

    public DeleteItemResponse delete(String employeeId) {
        return employeeRepository.delete(employeeId);
    }
}
